// ── Fake demo data — triggered by "antoinevalton12" easter egg ──────────────
export const DEMO_SITE_URL = 'https://usewok.com';
export const DEMO_DOMAIN = 'usewok.com';

export const DEMO_PROFILE = {
  site_url: DEMO_SITE_URL,
  identity_name: 'UseWok',
  identity_industry: 'SaaS · AI Visibility',
  identity_city: 'Paris',
  score_overall: 74,
  lrs_score: 74,
  score_ai_visibility: 68,
  score_message_clarity: 81,
  score_commercial_signal: 72,
  score_previous: 61,
  last_scan: new Date().toISOString(),
  chatgpt_score: 71,
  gemini_score: 78,
  claude_score: 65,
  perplexity_score: 58,
  mistral_score: 82,
  grok_score: 44,
  copilot_score: 61,
  llama_score: 53,
  has_schema_markup: true,
  has_google_business: false,
  has_ssl: true,
  has_mobile_friendly: true,
  has_sitemap: true,
  shock_insight: "UseWok est cité par Mistral et Gemini dans 78% des requêtes sur la visibilité IA, mais reste invisible pour Grok et Perplexity — deux moteurs en forte croissance.",
  organic_traffic: 12400,
  organic_keywords: 843,
  backlinks: 2100,
  authority_score: 34,
  issues: [
    { problem: "Aucune fiche Google My Business — pénalise les recherches locales et les requêtes géolocalisées sur les assistants IA." },
    { problem: "Contenu de la homepage trop générique — les LLM peinent à identifier votre catégorie précise." },
    { problem: "Pas de FAQ structurée — les IA ignorent vos questions/réponses clés lors des synthèses." },
    { problem: "Schema.org incomplet — Organisation et SoftwareApplication non déclarés." },
  ],
  injection_plan: [
    { action_title: "Créer et optimiser la fiche Google My Business", engine: "gemini", platform: "Google Maps", impact: "high", effort: "low", gap: "Grok et Gemini Maps ne vous citent jamais dans les résultats locaux." },
    { action_title: "Réécrire la homepage avec un positionnement IA clair", engine: "chatgpt", platform: "Votre site", impact: "high", effort: "medium", gap: "ChatGPT ne sait pas vous classer — 'visibilité IA' doit apparaître dès la balise H1." },
    { action_title: "Ajouter une page FAQ dédiée au format Question/Réponse", engine: "perplexity", platform: "Votre site", impact: "high", effort: "low", gap: "Perplexity cite en priorité les pages FAQ structurées." },
    { action_title: "Implémenter Schema.org SoftwareApplication", engine: "claude", platform: "Votre site", impact: "medium", effort: "medium", gap: "Claude lit les métadonnées structurées pour identifier les outils SaaS." },
    { action_title: "Publier 2 articles de blog experts par mois", engine: "mistral", platform: "Blog UseWok", impact: "medium", effort: "high", gap: "Votre score Mistral est bon mais dépend uniquement de la homepage." },
    { action_title: "Obtenir des citations sur ProductHunt et G2", engine: "perplexity", platform: "Plateformes tierces", impact: "high", effort: "medium", gap: "Perplexity favorise fortement les produits avec des avis tiers vérifiés." },
  ],
  competitors: [
    { name: "Semrush AI", domain: "semrush.com", lrs_score: 89 },
    { name: "BrightEdge", domain: "brightedge.com", lrs_score: 82 },
    { name: "Conductor", domain: "conductor.com", lrs_score: 76 },
  ],
  audit_data: {
    critical_issues: [
      { title: "Google My Business manquant", severity: "critical" },
      { title: "Schema.org incomplet", severity: "high" },
    ],
    warnings: 8,
    passed: 31,
  },
  perf_data: {
    share_of_voice: 18,
    share_of_voice_delta: +4,
    top_queries: ["visibilité ia", "référencement ia", "lrs score", "optimiser chatgpt"],
  },
  action_plan: [
    { title: "Créer et optimiser la fiche Google My Business" },
    { title: "Réécrire la homepage avec un positionnement IA clair" },
    { title: "Ajouter une page FAQ dédiée au format Question/Réponse" },
    { title: "Implémenter Schema.org SoftwareApplication" },
    { title: "Publier 2 articles de blog experts par mois" },
    { title: "Obtenir des citations sur ProductHunt et G2" },
  ],
};