import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Pencil, Check, X, Sparkles, BookOpen } from 'lucide-react';
import { toast } from 'sonner';
import { base44 } from '@/api/base44Client';
import { getActiveDomain, onActiveDomainChange } from '@/lib/active-domain';
import { getCachedUser, peekCache, setCache } from '@/lib/data-cache';
import {
  loadBrandKnowledge, saveBrandKnowledge, emptyBrandKnowledge,
  SCOPES,
} from '@/lib/brand-knowledge';
import { Section, FieldLabel, FieldValue, TextInput, TextArea, SelectInput, FieldDivider } from '@/components/brand/BrandField';
import TagListEditor, { PillList } from '@/components/brand/TagListEditor';

const F = "'Wix Madefor Text', 'Wix Madefor Display', 'Inter var', 'Inter', system-ui, sans-serif";
const INK = '#111827';
const INK3 = '#6B7280';
const BORDER = '#E5E7EB';
const BG = '#FFFFFF';
const VIOLET = '#7B4FE0';
const GREEN = '#059669';
const GREEN_BG = '#D1FAE5';

export default function BrandKnowledge() {
  const navigate = useNavigate();
  const _active0 = getActiveDomain();
  const _seed = peekCache(`bk_${_active0?.url || 'all'}`);
  const [profile, setProfile] = useState(_seed?.profile || null);
  const [extra, setExtra] = useState(_seed?.extra || {});
  const [k, setK] = useState(_seed?.knowledge || emptyBrandKnowledge());
  const [phase, setPhase] = useState(_seed ? 'ready' : 'loading');
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [dirty, setDirty] = useState(false);
  const [updatedAt, setUpdatedAt] = useState(null);
  const [user, setUser] = useState(null);

  const set = (field, value) => { setK(prev => ({ ...prev, [field]: value })); setDirty(true); };

  const load = async () => {
    const active = getActiveDomain();
    // Keep showing cached content instead of the full-screen spinner if we have it.
    setPhase(prev => (peekCache(`bk_${active?.url || 'all'}`) ? 'ready' : 'loading'));
    try {
      const u = await getCachedUser();
      setUser(u);
      const { profile: p, extra: ex, knowledge } = await loadBrandKnowledge(active?.url);
      if (!p) { if (!peekCache(`bk_${active?.url || 'all'}`)) setPhase('no_profile'); return; }
      setProfile(p); setExtra(ex); setK(knowledge);
      setUpdatedAt(ex.brand_knowledge_updated_at || null);
      setDirty(false);
      setEditMode(false);
      setPhase('ready');
      setCache(`bk_${active?.url || 'all'}`, { profile: p, extra: ex, knowledge });
    } catch { if (!peekCache(`bk_${active?.url || 'all'}`)) setPhase('no_profile'); }
  };

  useEffect(() => {
    load();
    const unsub = onActiveDomainChange(() => load());
    return unsub;
  }, []);

  const save = async () => {
    if (!profile) return;
    setSaving(true);
    try {
      const newExtra = await saveBrandKnowledge(profile, extra, k);
      setExtra(newExtra);
      setUpdatedAt(newExtra.brand_knowledge_updated_at);
      setDirty(false);
      setEditMode(false);
      setCache(`bk_${profile?.site_url || 'all'}`, { profile, extra: newExtra, knowledge: k });
      toast.success('Brand Knowledge saved');
    } catch {
      toast.error('Failed to save');
    } finally { setSaving(false); }
  };

  const cancelEdit = () => {
    load();
  };

  const generate = async () => {
    if (!profile?.site_url) return;
    setGenerating(true);
    try {
      const res = await base44.functions.invoke('generateBrandKnowledge', {
        url: profile.site_url,
        business_name: k.business_name || profile.identity_name || '',
      });
      if (!res?.data || res.data.error) { toast.error(res?.data?.error || 'Failed to generate'); setGenerating(false); return; }
      const gen = res.data.knowledge || {};
      setK(prev => ({
        ...prev,
        ...gen,
        business_name: gen.business_name || prev.business_name,
        site_url: prev.site_url,
      }));
      setDirty(true);
      setEditMode(true);
      toast.success('Brand Knowledge generated by AI — review and save');
    } catch {
      toast.error('AI generation failed');
    } finally { setGenerating(false); }
  };

  if (phase === 'loading') {
    return (
      <div style={{ minHeight: '100vh', background: BG, fontFamily: F, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div style={{ width: 28, height: 28, borderRadius: '50%', border: `3px solid ${BORDER}`, borderTopColor: VIOLET, animation: 'spin 0.8s linear infinite' }} />
        <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
      </div>
    );
  }

  if (phase === 'no_profile') {
    return (
      <div style={{ minHeight: '100vh', background: BG, fontFamily: F, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: 32, textAlign: 'center' }}>
        <div style={{ width: 52, height: 52, borderRadius: 14, background: '#F9FAFB', border: `1px solid ${BORDER}`, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 14 }}>
          <BookOpen size={22} color={INK3} />
        </div>
        <p style={{ fontSize: 15, fontWeight: 700, color: INK, margin: '0 0 6px' }}>No site analyzed</p>
        <p style={{ fontSize: 12, color: INK3, margin: '0 0 16px' }}>Analyze your site from the home page to fill in your Brand Knowledge.</p>
        <button onClick={() => navigate('/app')} style={{ padding: '10px 20px', background: INK, color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 700, cursor: 'pointer', fontFamily: F }}>← Home</button>
      </div>
    );
  }

  const domainLabel = (profile?.site_url || '').replace(/https?:\/\//, '').split('/')[0];
  const userName = user?.full_name || user?.email?.split('@')[0] || '—';
  const userRole = user?.role === 'admin' ? 'Admin' : 'User';
  const meta = updatedAt
    ? `Updated by: ${userName} | ${userRole} · ${new Date(updatedAt).toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' })}`
    : `Generated by AI · ${domainLabel}`;
  const isSaved = !dirty && updatedAt;

  return (
    <div style={{ minHeight: '100vh', background: BG, fontFamily: F }}>
      {/* Header */}
      <div style={{ padding: '24px 32px 16px', display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 16, borderBottom: `1px solid ${BORDER}` }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <h1 style={{ fontSize: 22, fontWeight: 800, color: INK, margin: 0, letterSpacing: '-0.02em' }}>Brand Knowledge</h1>
            {isSaved && (
              <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, padding: '3px 10px', background: GREEN_BG, color: GREEN, borderRadius: 999, fontSize: 11, fontWeight: 600 }}>
                <Check size={11} /> Saved
              </span>
            )}
            {dirty && (
              <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, padding: '3px 10px', background: '#FEF3C7', color: '#D97706', borderRadius: 999, fontSize: 11, fontWeight: 600 }}>
                Draft
              </span>
            )}
          </div>
          <p style={{ fontSize: 12.5, color: INK3, margin: '4px 0 0' }}>Tell the AI who you are — the clearer it is, the better it talks about you.</p>
        </div>
        <div style={{ display: 'flex', gap: 8, flexShrink: 0 }}>
          {!editMode ? (
            <>
              <button onClick={generate} disabled={generating}
                style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '8px 14px', border: `1px solid ${BORDER}`, background: '#fff', borderRadius: 8, fontSize: 12.5, fontWeight: 600, color: VIOLET, cursor: generating ? 'default' : 'pointer', opacity: generating ? 0.6 : 1, fontFamily: F }}>
                {generating
                  ? <span style={{ width: 12, height: 12, borderRadius: '50%', border: '2px solid rgba(123,79,224,0.3)', borderTopColor: VIOLET, animation: 'spin 0.7s linear infinite' }} />
                  : <Sparkles size={13} />}
                {generating ? 'Generating…' : 'Generate with AI'}
              </button>
              <button onClick={() => setEditMode(true)}
                style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '8px 14px', border: `1px solid ${BORDER}`, background: '#F9FAFB', borderRadius: 8, fontSize: 12.5, fontWeight: 600, color: INK, cursor: 'pointer', fontFamily: F }}>
                <Pencil size={13} color={VIOLET} /> Edit
              </button>
            </>
          ) : (
            <>
              <button onClick={cancelEdit} disabled={saving}
                style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '8px 14px', border: `1px solid ${BORDER}`, background: '#fff', borderRadius: 8, fontSize: 12.5, fontWeight: 600, color: INK3, cursor: 'pointer', fontFamily: F }}>
                <X size={13} /> Cancel
              </button>
              <button onClick={save} disabled={saving}
                style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '8px 16px', border: 'none', background: VIOLET, borderRadius: 8, fontSize: 12.5, fontWeight: 700, color: '#fff', cursor: 'pointer', fontFamily: F }}>
                {saving ? <span style={{ width: 12, height: 12, borderRadius: '50%', border: '2px solid rgba(255,255,255,0.4)', borderTopColor: '#fff', animation: 'spin 0.7s linear infinite' }} /> : <Check size={13} />}
                Save
              </button>
            </>
          )}
        </div>
      </div>

      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
        style={{ maxWidth: 820, margin: '0 auto', padding: '20px 32px 120px' }}>

        {/* Who you are */}
        <Section title="Who you are" icon="🏷️" hint="Basic info about your business. This is what AI should know first.">
          {editMode ? (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
              <div>
                <FieldLabel>Business name</FieldLabel>
                <TextInput value={k.business_name} onChange={v => set('business_name', v)} placeholder="e.g. UseWok" />
              </div>
              <div>
                <FieldLabel>Your industry</FieldLabel>
                <TextInput value={k.industry} onChange={v => set('industry', v)} placeholder="e.g. marketing software" />
              </div>
              <div>
                <FieldLabel>Website address</FieldLabel>
                <TextInput value={k.site_url} onChange={v => set('site_url', v)} placeholder="usewok.com" />
              </div>
              <div>
                <FieldLabel>Where are you based?</FieldLabel>
                <TextInput value={k.headquarters} onChange={v => set('headquarters', v)} placeholder="e.g. Paris, France" />
              </div>
            </div>
          ) : (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
              <div><FieldLabel>Business name</FieldLabel><FieldValue value={k.business_name} /></div>
              <div><FieldLabel>Your industry</FieldLabel><FieldValue value={k.industry} /></div>
              <div><FieldLabel>Website address</FieldLabel><FieldValue value={k.site_url} /></div>
              <div><FieldLabel>Where are you based?</FieldLabel><FieldValue value={k.headquarters} /></div>
            </div>
          )}
        </Section>

        {/* Who you sell to */}
        <Section title="Who you sell to" icon="🎯" hint="Describe your customers: who they are and where they are.">
          {editMode ? (
            <>
              <FieldLabel>Your typical customers</FieldLabel>
              <TextArea value={k.audience} onChange={v => set('audience', v)} rows={2} placeholder="e.g. SMB owners, marketing managers…" />
              <FieldDivider />
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                <div>
                  <FieldLabel>What type of customers?</FieldLabel>
                  <TextInput value={k.target_segment} onChange={v => set('target_segment', v)} placeholder="e.g. small businesses" />
                </div>
                <div>
                  <FieldLabel>Where do you sell?</FieldLabel>
                  <SelectInput value={k.scope} onChange={v => set('scope', v)} options={SCOPES.map(s => ({ value: s, label: s }))} />
                </div>
              </div>
            </>
          ) : (
            <>
              <FieldLabel>Your typical customers</FieldLabel>
              <FieldValue value={k.audience} />
              <FieldDivider />
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                <div><FieldLabel>What type of customers?</FieldLabel><FieldValue value={k.target_segment} /></div>
                <div><FieldLabel>Where do you sell?</FieldLabel><FieldValue value={k.scope} /></div>
              </div>
            </>
          )}
        </Section>

        {/* What makes you unique */}
        <Section title="What makes you unique" icon="💎" hint="Why a customer would choose you over a competitor. Add up to 5 strengths.">
          {editMode ? (
            <>
              <FieldLabel>In one sentence, what do you do best?</FieldLabel>
              <TextArea value={k.value_description} onChange={v => set('value_description', v)} rows={3} placeholder="e.g. we help businesses appear in ChatGPT answers…" />
              <FieldDivider />
              <FieldLabel>Your strengths (5 max)</FieldLabel>
              <TagListEditor items={k.value_keywords} onChange={v => set('value_keywords', v)} placeholder="e.g. easy to use, fast results…" />
            </>
          ) : (
            <>
              <FieldLabel>In one sentence, what do you do best?</FieldLabel>
              <FieldValue value={k.value_description} />
              <FieldDivider />
              <FieldLabel>Your strengths</FieldLabel>
              <PillList items={k.value_keywords} />
            </>
          )}
        </Section>

        {/* How people use you */}
        <Section title="How people use you" icon="🛠️" hint="Concrete situations where your customers call on you. 5 max.">
          {editMode ? (
            <TagListEditor items={k.use_cases} onChange={v => set('use_cases', v)} placeholder="e.g. check your AI presence…" />
          ) : (
            <PillList items={k.use_cases} />
          )}
        </Section>

        {/* Your expertise topics */}
        <Section title="Your expertise topics" icon="🧠" hint="Topics where you're recognized as an expert. 5 max.">
          {editMode ? (
            <TagListEditor items={k.authority_topics} onChange={v => set('authority_topics', v)} placeholder="e.g. AI visibility, SEO…" />
          ) : (
            <PillList items={k.authority_topics} />
          )}
        </Section>

        {/* What your customers wonder */}
        <Section title="What your customers wonder" icon="❓" hint="Questions people ask before buying from you. 5 max.">
          {editMode ? (
            <TagListEditor items={k.pre_purchase_questions} onChange={v => set('pre_purchase_questions', v)} placeholder="e.g. how to get cited by AI?" />
          ) : (
            <PillList items={k.pre_purchase_questions} />
          )}
        </Section>

        {/* Purchase barriers */}
        <Section title="Purchase barriers" icon="🚧" hint="Common hesitations or objections you need to overcome. 5 max.">
          {editMode ? (
            <TagListEditor items={k.objections} onChange={v => set('objections', v)} placeholder="e.g. is it hard to set up?" />
          ) : (
            <PillList items={k.objections} />
          )}
        </Section>

        {/* Topics to avoid */}
        <Section title="Topics to avoid" icon="🙅" hint="Topics you definitely don't want associated with you.">
          {editMode ? (
            <>
              <FieldLabel>Topics to avoid</FieldLabel>
              <TextArea value={k.avoid_topics?.join(', ')} onChange={v => set('avoid_topics', v.split(',').map(s => s.trim()).filter(Boolean))} rows={2} placeholder="e.g. sensitive topics, competitors…" />
            </>
          ) : (
            <>
              <FieldLabel>Topics to avoid</FieldLabel>
              {k.avoid_topics?.length > 0
                ? <PillList items={k.avoid_topics} />
                : <FieldValue value={null} />}
            </>
          )}
        </Section>
      </motion.div>

      {/* Bottom save bar when dirty and in edit mode */}
      {dirty && editMode && (
        <motion.div initial={{ y: 60 }} animate={{ y: 0 }}
          style={{ position: 'fixed', bottom: 0, left: 0, right: 0, zIndex: 30, background: '#fff', borderTop: `1px solid ${BORDER}`, padding: '12px 32px', display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 10, boxShadow: '0 -4px 20px rgba(0,0,0,0.06)' }}>
          <span style={{ fontSize: 12.5, color: INK3, marginRight: 'auto' }}>Unsaved changes</span>
          <button onClick={cancelEdit} style={{ padding: '8px 16px', border: `1px solid ${BORDER}`, background: '#fff', borderRadius: 8, fontSize: 12.5, fontWeight: 600, color: INK3, cursor: 'pointer', fontFamily: F }}>Cancel</button>
          <button onClick={save} disabled={saving} style={{ padding: '8px 20px', border: 'none', background: VIOLET, borderRadius: 8, fontSize: 12.5, fontWeight: 700, color: '#fff', cursor: 'pointer', fontFamily: F }}>
            {saving ? 'Saving…' : 'Save'}
          </button>
        </motion.div>
      )}
    </div>
  );
}