import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Shield, FileText, ChevronRight } from 'lucide-react';

const blur = (delay = 0) => ({
  initial: { opacity: 0, filter: 'blur(12px)', y: 6 },
  animate: { opacity: 1, filter: 'blur(0px)', y: 0 },
  transition: { duration: 0.55, delay, ease: [0.22, 1, 0.36, 1] },
});

const TERMS = [
  {
    title: 'Acceptance of Terms',
    body: `By accessing and using Stensor, you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the service.

Stensor is an AI-powered financial coaching platform. It is not a licensed financial advisory service. All information provided is for educational and informational purposes only.`,
  },
  {
    title: 'Nature of the Service',
    body: `Stensor uses artificial intelligence to provide personalized financial guidance, insights, and coaching. Our AI analyzes your inputs to generate responses tailored to your situation.

Important: Stensor is not a substitute for professional financial advice. The content generated by our AI should not be considered as regulated financial advice, investment recommendations, or legal counsel. For significant financial decisions, always consult a certified financial advisor.`,
  },
  {
    title: 'User Accounts & Credits (Tensors)',
    body: `You are responsible for maintaining the confidentiality of your account credentials. Tensors are our credit system — each interaction with the AI consumes Tensors based on complexity and selected AI mode.

Tensor allocations are plan-based and reset monthly. Unused Tensors do not carry over between billing periods. Credits are non-transferable and non-refundable.`,
  },
  {
    title: 'Acceptable Use',
    body: `You agree not to use Stensor to:
- Violate any applicable laws or regulations
- Attempt to reverse-engineer or exploit the AI systems
- Share account credentials or resell access
- Submit false, misleading, or harmful content

We reserve the right to suspend or terminate accounts that violate these policies without prior notice.`,
  },
  {
    title: 'Intellectual Property',
    body: `All platform content, trademarks, AI models, and interfaces are the exclusive property of Stensor. You are granted a limited, non-exclusive, non-transferable license to use the platform for personal, non-commercial purposes.

Content you create through the platform (conversation transcripts, outputs) remains yours. You grant Stensor a license to use anonymized interactions to improve our AI systems.`,
  },
  {
    title: 'Limitation of Liability',
    body: `To the maximum extent permitted by law, Stensor shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.

Financial decisions made based on AI-generated content are made at your own risk. Stensor provides no guarantee of financial outcomes.`,
  },
  {
    title: 'Modifications',
    body: `Stensor reserves the right to modify these terms at any time. Changes will be communicated via email or in-app notification. Continued use of the service after changes constitutes acceptance of the new terms.`,
  },
];

const PRIVACY = [
  {
    title: 'Data We Collect',
    body: `We collect the following information to operate the service:
- Account information: name, email address
- Usage data: conversation history, Tensor consumption, feature usage
- Technical data: device type, IP address, browser information

We never collect government ID, social security numbers, or bank account credentials.`,
  },
  {
    title: 'How We Use Your Data',
    body: `Your data is used exclusively to:
- Provide and improve the Stensor service
- Personalize AI responses based on your conversation history
- Analyze platform usage to enhance features
- Send transactional communications (plan updates, security alerts)

We do not sell your personal data to third parties. Ever.`,
  },
  {
    title: 'Data Storage & Security',
    body: `Your data is stored securely on Base44 infrastructure with industry-standard encryption at rest and in transit. Conversation data is stored to enable your history and AI personalization.

We implement technical and organizational measures to protect your data against unauthorized access, loss, or disclosure.`,
  },
  {
    title: 'Your Rights',
    body: `You have the right to:
- Access: Request a copy of all data we hold about you
- Rectification: Correct inaccurate personal data
- Erasure: Request deletion of your account and all associated data
- Portability: Receive your data in a portable format

To exercise these rights, contact us at: privacy@stensor.app`,
  },
  {
    title: 'Cookies',
    body: `Stensor uses only essential session cookies required for authentication and app functionality. We do not use advertising cookies, tracking pixels, or third-party analytics that compromise your privacy.`,
  },
  {
    title: 'Third-Party Services',
    body: `Stensor uses the following trusted third-party providers:
- Base44: Application infrastructure and database hosting
- Stripe: Payment processing (we never see your full card details)
- AI providers: For generating responses (data is not used to train their general models under our agreements)`,
  },
  {
    title: 'Data Retention',
    body: `We retain your account data for as long as your account is active. Upon account deletion, personal data is removed within 30 days. Anonymized, aggregated usage statistics may be retained indefinitely for platform improvement.`,
  },
];

const TABS = [
  { id: 'terms', label: 'Terms of Use', icon: FileText },
  { id: 'privacy', label: 'Privacy Policy', icon: Shield },
];

export default function LegalPage() {
  const [active, setActive] = useState('terms');
  const sections = active === 'terms' ? TERMS : PRIVACY;

  return (
    <div className="min-h-screen font-be" style={{ background: 'linear-gradient(135deg, #fafafa 0%, #f5f5f5 100%)' }}>
      <div className="max-w-2xl mx-auto px-4 py-14">

        {/* Header */}
        <motion.div {...blur(0)} className="mb-10">
          <h1 className="text-3xl font-black text-fg mb-2">Legal</h1>
          <p className="text-sm text-zinc-400">Last updated: April 2026</p>
        </motion.div>

        {/* Tabs */}
        <motion.div {...blur(0.08)} className="flex gap-2 mb-10 p-1.5 bg-white border border-border rounded-2xl w-fit">
          {TABS.map(tab => {
            const Icon = tab.icon;
            const isActive = active === tab.id;
            return (
              <button key={tab.id} onClick={() => setActive(tab.id)}
                className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold transition-all ${isActive ? 'bg-fg text-white shadow-md' : 'text-zinc-500 hover:text-fg'}`}>
                <Icon className="w-4 h-4" />
                {tab.label}
              </button>
            );
          })}
        </motion.div>

        {/* Sections */}
        <AnimatePresence mode="wait">
          <motion.div key={active}
            initial={{ opacity: 0, filter: 'blur(8px)' }}
            animate={{ opacity: 1, filter: 'blur(0px)' }}
            exit={{ opacity: 0, filter: 'blur(8px)' }}
            transition={{ duration: 0.35, ease: [0.22, 1, 0.36, 1] }}
            className="space-y-5">
            {sections.map((section, i) => (
              <motion.div key={section.title}
                initial={{ opacity: 0, y: 8, filter: 'blur(6px)' }}
                animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
                transition={{ delay: i * 0.04, duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
                className="bg-white border border-border rounded-2xl p-6">
                <div className="flex items-center gap-2.5 mb-3">
                  <div className="w-6 h-6 flex items-center justify-center bg-yuzu rounded-lg flex-shrink-0">
                    <ChevronRight className="w-3 h-3 text-fg" />
                  </div>
                  <h2 className="text-sm font-black text-fg">{section.title}</h2>
                </div>
                <p className="text-sm text-zinc-500 leading-relaxed whitespace-pre-line">{section.body}</p>
              </motion.div>
            ))}
          </motion.div>
        </AnimatePresence>

        <motion.p {...blur(0.3)} className="text-xs text-zinc-300 text-center mt-12">
          Questions? Contact us at <span className="text-fg font-semibold">legal@stensor.app</span>
        </motion.p>
      </div>
    </div>
  );
}